### ISSUE TITLE
Renovate v9

### ISSUE THREAD

**Issue by rarkins** [singapore/renovate#298]
This issue to store a list of breaking changes to be implemented in a future v9.

- [ ] #405 - Refactor lock file maintenance configuration
- [ ] #406 - Remove `{{changelog}}` (pre-formatted markdown) from template context
- [ ] #407 - Refactor group configuration
